# Generated by Django 5.0.6 on 2024-05-16 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subjectName', models.CharField(max_length=50)),
                ('subjectCode', models.IntegerField(unique=True)),
                ('number_of_classes', models.IntegerField()),
            ],
        ),
    ]
