# Generated by Django 5.0.6 on 2024-05-16 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectCode',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
