# Generated by Django 5.0.1 on 2024-05-31 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_attendance_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='attendance',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
