# Generated by Django 5.0.6 on 2024-05-16 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0002_alter_subject_subjectcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subjectCode',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subjectName',
            field=models.CharField(max_length=100),
        ),
    ]
