# Generated by Django 5.0.1 on 2024-05-20 07:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0003_alter_subject_subjectcode_alter_subject_subjectname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(code='invalid_password', message='Password must contain at least one special character, one letter, one digit, and be at least 8 characters long.', regex='^(?=.*[!@#$%^&*()_+}{":;\'?\\/.,`~])(?=.*[a-zA-Z])(?=.*\\d).{8,}$')])),
                ('phone_number', models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_phone_number', message='Phone number must be 10 digits long.', regex='^\\d{10}$')])),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='subject',
            name='number_of_classes',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
