# Generated by Django 5.0.1 on 2024-05-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0004_teacher_alter_subject_number_of_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='number_of_classes',
            field=models.IntegerField(),
        ),
    ]
