# Generated by Django 5.0.1 on 2024-06-02 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendence', '0005_alter_group_student_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='student_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='attendence.student'),
            preserve_default=False,
        ),
    ]
